<?php

namespace ProjectBundle\Repository;

/**
 * CustomerPaymentLinepayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerPaymentLinepayRepository extends \Doctrine\ORM\EntityRepository
{
}
